apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: findmyrelative-ui-pipeline
spec:
  resources:
  - name: source-git-repo
    type: git
  - name: image-resource-name
    type: image
  tasks:
  - name: build-image
    taskRef:
      name: buildah-v0-8-0
      kind: ClusterTask
    resources:
      inputs:
      - name: source
        resource: source-git-repo
      outputs:
      - name: image
        resource: image-resource-name
    params:
    - name: TLSVERIFY
      value: "false"
  - name: create-upate-deployment
    taskRef:
      name: openshift-client
      kind: ClusterTask
    runAfter:
      - build-image
    params:
      - name: ARGS
        value:
          - apply
          - -f
          - https://raw.githubusercontent.com/SM43/findmyrelative-frontend/master/k8s/deployment.yaml
